### ISSUE TITLE
single page

### ISSUE THREAD

**Issue by MahmudSuleman** [AAbdul-Rahim/chairman#1]
![Screenshot (148)](https://user-images.githubusercontent.com/38923023/89118682-0b1fb900-d497-11ea-90e1-aab77b88719d.png)
the style for single page broken

**Comment by AAbdul-Rahim** [comment]
https://www.linkedin.com/in/alhassan-abdul-rahim-6225ab132/

**Comment by AAbdul-Rahim** [comment]
https://www.linkedin.com/in/alhassan-abdul-rahim-6225ab132/

**Comment by ahmedzelia** [comment]
Awesome

**Comment by ahmedzelia** [comment]
Not bad

**Comment by MahmudSuleman** [comment]
not applicable anymore
